### ISSUE TITLE
Implement retry on connection errors

### ISSUE THREAD

**Issue by Almad** [apiaryio/black-belt#117]
```
Waiting for tests to pass...
...............Traceback (most recent call last):
  File "/usr/local/bin/bb", line 5, in <module>
    main()
  File "/Library/Python/2.7/site-packages/blackbelt/tasks.py", line 32, in main
    cli()
  File "/Library/Python/2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/blackbelt/commands/gh.py", line 50, in deploy
    deploy_command(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/blackbelt/commands/gh.py", line 59, in deploy_command
    do_deploy(pr_url)
  File "/Library/Python/2.7/site-packages/blackbelt/handle_github.py", line 272, in deploy
    name=merge_info['name']
  File "/Library/Python/2.7/site-packages/blackbelt/circle.py", line 89, in wait_for_tests
    number=build['build_num']
  File "/Library/Python/2.7/site-packages/blackbelt/circle.py", line 60, in get_build
    return self.request('get', url)
  File "/Library/Python/2.7/site-packages/blackbelt/circle.py", line 37, in request
    res = getattr(requests, method)(url, headers=self.default_headers)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known'))
```

**Comment by abtris** [comment]
Migrated to apiaryio/bb#32
