### ISSUE TITLE
PR required checks raises an exception

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#136]
I'm getting an exception instead of prompt if the PR checks fail:

```
$ bb gh deploy https://github.com/apiaryio/apiary/pull/4935
PR state: open
Traceback (most recent call last):
  File "/usr/local/bin/bb", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/blackbelt/tasks.py", line 32, in main
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/blackbelt/commands/gh.py", line 51, in deploy
    deploy_command(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/blackbelt/commands/gh.py", line 60, in deploy_command
    do_deploy(pr_url)
  File "/usr/local/lib/python2.7/site-packages/blackbelt/handle_github.py", line 336, in deploy
    merge_info = merge(pr_url)
  File "/usr/local/lib/python2.7/site-packages/blackbelt/handle_github.py", line 182, in merge
    verify_pr_required_checks(pr_details)
  File "/usr/local/lib/python2.7/site-packages/blackbelt/handle_github.py", line 277, in verify_pr_required_checks
    raise ValueError(message)
ValueError: PR required checks (3): failure
```

**Comment by abtris** [comment]
some problem with python 3

**Comment by abtris** [comment]
Migrated to apiaryio/bb#26
