### ISSUE TITLE
gh deploy resulting in `TypeError: expected string or bytes-like object`

### ISSUE THREAD

**Issue by opichals** [apiaryio/black-belt#164]
Using `bb version` = `0.15.10` and issuing
```
bb gh deploy https://github.com/apiaryio/.../pull/12234
```

I got  the following error at the end

```
Waiting for tests to pass...
.........................
Ready for deploy! Do you want me to deploy b70d1b4223c2eaa5b60428aa92006786fedbe953 as the new version of Apiary? [y/N]: y
SSL_PORT is set to other value than 9000; GitHub login will not work
SSL_PORT is set to other value than 9000; GitHub login will not work
SSL_PORT is set to other value than 9000; GitHub login will not work
Traceback (most recent call last):
  File "/usr/local/bin/bb", line 5, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/blackbelt/tasks.py", line 32, in main
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/blackbelt/commands/gh.py", line 51, in deploy
    deploy_command(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/blackbelt/commands/gh.py", line 60, in deploy_command
    do_deploy(pr_url)
  File "/usr/local/lib/python3.6/site-packages/blackbelt/handle_github.py", line 394, in deploy
    ticket_id = get_pr_ticket_id(merge_info['description'])
  File "/usr/local/lib/python3.6/site-packages/blackbelt/handle_github.py", line 333, in get_pr_ticket_id
    match = re.search(PR_PHRASE_PREFIX + ' ' + r"\[.*\]\(https://trello.com/c/(?P<id>\w+)/.*\)", description)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

**Comment by Almad** [comment]
What is the Python version?

**Comment by opichals** [comment]
```
$ `type -p bb | xargs head -n 1 | cut -c 3-` --version
Python 3.6.4
```

**Comment by kylef** [comment]
Was the pull request that caused this https://github.com/apiaryio/apiary/pull/5380 ? you seem to have changed the argument to invalid one? If so, I wonder if it is because it has empty description, perhaps API returns null and therefore the description past to `re.search(PR_PHRASE_PREFIX + ' ' + r"\[.*\]\(https://trello.com/c/(?P<id>\w+)/.*\)", description)` is actually `None` thus causing the `TypeError`

**Comment by opichals** [comment]
Nope, it was this one https://github.com/apiaryio/apiary/pull/5377

**Comment by kylef** [comment]
I tested my guess about empty descriptions out and GitHub API does return an empty string instead of None. Not sure how to reproduce this one. I tested by applying patch to my black-belt dev version:

```diff
diff --git a/blackbelt/handle_github.py b/blackbelt/handle_github.py
index ab6c723..3a92b38 100644
--- a/blackbelt/handle_github.py
+++ b/blackbelt/handle_github.py
@@ -178,6 +178,8 @@ def merge(pr_url):
     """

     pr_details = get_pr_details(pr_url)
+    print(get_pr_ticket_id(pr_details['body']))
+    raise Exception('prevent next steps and deploy')

     # Check if PR is ready to merge - OPEN status
     verify_pr_state(pr_details)
```

This patch for you should raise the same exception as before, perhaps using it we can debug this further on your end.

**Comment by opichals** [comment]
Got the same thing yesterday with https://github.com/apiaryio/apiary/pull/5382 deploy.

Thanks! Will apply the patch and report later as I get to do another deploy.

**Comment by kylef** [comment]
@opichals Want to add `pr_details(['body'])` after `pr_details = get_pr_details(pr_url)` so we can see what type body is?

**Comment by opichals** [comment]
@kylef Sure, the result of `print(pr_details['body'])` is `None`

**Comment by abtris** [comment]
Migrated to apiaryio/bb#23
