### ISSUE TITLE
bb not worky on debian

### ISSUE THREAD

**Issue by Almad** [apiaryio/black-belt#70]
```
almad@arael:~/projects/internal-docs$ bb gh merge https://github.com/apiaryio/repo/pull/95
Traceback (most recent call last):
  File "/usr/local/bin/bb", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/blackbelt/tasks.py", line 30, in main
    cli()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 609, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 589, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 930, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 969, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python2.7/dist-packages/blackbelt/tasks.py", line 22, in get_command
    eval(code, ns, ns)
  File "/usr/local/lib/python2.7/dist-packages/blackbelt/commands/gh.py", line 3, in <module>
    from blackbelt.handle_github import (
  File "/usr/local/lib/python2.7/dist-packages/blackbelt/handle_github.py", line 10, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

**Comment by abtris** [comment]
Please retest, we add missing requirements.

**Comment by honzajavorek** [comment]
@Almad still relevant?

**Comment by Almad** [comment]
@honzajavorek not sure, let me retest (in Docker :trollface: ) in some time.

**Comment by abtris** [comment]
Migrated to apiaryio/bb#37
