### ISSUE TITLE
Deploy crashes on HipChat integration

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/black-belt#93]
I had no time to investigate further, but I have correct HipChat API token, that's for sure (double checked, performed `bb init`). Annoying fact: it tears down the whole deploy, so you need to continue manually.

```
...
#2500 merged!
Traceback (most recent call last):
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/bin/bb", line 5, in <module>
    main()
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/blackbelt/tasks.py", line 30, in main
    cli()
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/blackbelt/commands/gh.py", line 50, in deploy
    deploy_command(*args, **kwargs)
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/blackbelt/commands/gh.py", line 59, in deploy_command
    do_deploy(pr_url)
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/blackbelt/handle_github.py", line 260, in deploy
    merge_info = merge(pr_url)
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/blackbelt/handle_github.py", line 220, in merge
    'commits': pr['commits']
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/blackbelt/messages.py", line 6, in post_message
    hipchat_post_message(message)
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/blackbelt/hipchat.py", line 6, in post_message
    client.post_message(message)
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/blackbelt/apis/hipchat.py", line 49, in post_message
    'message_format': 'text'
  File "/Users/honzajavorek/Workspace/apiary/env-apiary/lib/python2.7/site-packages/blackbelt/apis/hipchat.py", line 35, in request
    raise ValueError("Request to URL %s failed" % url)
ValueError: Request to URL https://api.hipchat.com/v2/room/Engine%20Room/notification?auth_token=hadoofRMEj9WsxxL7cpcd6FRCIlxmYUCE5zIhVkM failed
```

**Comment by kylef** [comment]
I guess this is no longer relevant and instead HipChat should just be removed from blackbelt? :wink:

**Comment by Almad** [comment]
:+1:
