### ISSUE TITLE
bb gh merge failing TypeError: post_message() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by freaz** [apiaryio/black-belt#99]
Today updated black.belt with: ```sudo pip install --upgrade blackbelt```

```
> bb gh merge https://github.com/apiaryio/apiary/pull/2625
remote: Counting objects: 530, done.
remote: Compressing objects: 100% (454/454), done.
remote: Total 530 (delta 301), reused 51 (delta 51), pack-reused 22
Receiving objects: 100% (530/530), 156.83 KiB | 0 bytes/s, done.
Resolving deltas: 100% (305/305), completed with 28 local objects.
From github.com:apiaryio/apiary
 * [new branch]      XVincentX/bug-scrolling-v3-in-firefox-results-in-jumping-back-to-top -> origin/XVincentX/bug-scrolling-v3-in-firefox-results-in-jumping-back-to-top
 + 327eb37...027a594 baggz/application-header-component -> origin/baggz/application-header-component  (forced update)
 + eb8a1da...d403405 honzajavorek/a-deep-guttural-sound -> origin/honzajavorek/a-deep-guttural-sound  (forced update)
   16ad1af..4272342  kubula/missing_currentPage_and_other_unified_header_renderer_stuff -> origin/kubula/missing_currentPage_and_other_unified_header_renderer_stuff
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 382 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
To git@github.com:apiaryio/apiary.git
   c804469..eaf0a8c  master -> master
#2625 merged!
Traceback (most recent call last):
  File "/usr/local/bin/bb", line 5, in <module>
    main()
  File "/Library/Python/2.7/site-packages/blackbelt/tasks.py", line 30, in main
    cli()
  File "/Library/Python/2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/blackbelt/commands/gh.py", line 35, in merge
    merge_command(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/blackbelt/commands/gh.py", line 44, in merge_command
    do_merge(pr_url)
  File "/Library/Python/2.7/site-packages/blackbelt/handle_github.py", line 221, in merge
    }, "#deploy-queue")
TypeError: post_message() takes exactly 1 argument (2 given)
```

**Comment by abtris** [comment]
Please retest with 0.11.12

**Comment by honzajavorek** [comment]
Hmm, I had to overlook this during CR :(

On Tue, Jun 16, 2015 at 2:13 PM, Ladislav Prskavec <notifications@github.com
